params:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/mobile?zeroDateTimeBehavior=convertToNull
    connectionTimeout: 600000
    username: root
    password: pastrav97
    maximumPoolSize: 15
    initialize: true